# fly.toml app configuration file generated for tftdle-backend-bold-smoke-2030 on 2025-02-01T01:36:07-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tftdle-backend-bold-smoke-2030'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.ports]]
  handlers = ["http"]
  port = 80

  [[http_service.ports]]
  handlers = ["tls", "http"]
  port = 443


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
